version: '3.8'

services:
    # Laravel application service
    app:
        build: .docker
        container_name: laravel_app
        ports:
            - "8000:80" # Expose Apache on port 8080
        volumes:
            - .:/var/www/html # Sync current directory to container's /var/www/html
            - ./.docker/volumes/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        depends_on:
            - mysql

    # MySQL service
    mysql:
        image: mysql:latest
        container_name: mysql
        volumes:
            - ./.docker/volumes/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234
        ports:
            - "3307:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - mysql
        ports:
            - "8001:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306

